 collections: # A list of collections the CMS should be able to edit
  - name: 'post' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Post' # Used in the UI, ie.: "New Post"
    folder: 'src/content/blog' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Hero Image', name: 'hero', widget: 'string' }
      - { label: 'Updated Date', name: 'updatedDate', widget: 'datetime' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }

  backend:
    name: git-gateway
    branch: main
  
media_folder: 'public/images/uploads' # Folder where user uploaded files should go
public_folder: '/images/uploads'