collections:
  - name: "post"
    label: "Post"
    folder: "src/content/blog"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Hero Image", name: "hero", widget: "string" }
      - { label: "Updated Date", name: "updatedDate", widget: "datetime" }
      - { label: "Publish Date", name: "date", widget: "datetime" }

backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"
